/*
 * generated by Xtext
 */
package org.guicecon.modules.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GuiceModulesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.guicecon.modules.ui.internal.GuiceModulesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.guicecon.modules.ui.internal.GuiceModulesActivator.getInstance().getInjector("org.guicecon.modules.GuiceModules");
	}
	
}
